In [29]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [42]:
# Load data
cs_file = '../data/SMB_input_four_ERA5.csv'

df = pd.read_csv(cs_file,
   delimiter='\t', index_col=['Date'],
    parse_dates=['Date'], na_values='NAN')
label_stake = df.drop_duplicates(subset=['Stake']).reset_index()[['Stake', 'Latitude', 
                                                                 'Longitude', 'Elevation']]

In [43]:
num_obs = []
for i in label_stake['Stake']:
    stake  = df.loc[lambda df1: df1['Stake'] == i, :].copy().reset_index()
    num_obs.append(stake['Stake'].count())

In [44]:
label_stake['n_obs'] = num_obs

In [45]:
label_stake

       Stake   Latitude  Longitude  Elevation  n_obs
0       PG01 -62.201488 -58.583236      435.7      6
1       PG02 -62.208882 -58.583777      385.2     11
2       PG03 -62.217533 -58.587279      346.4     10
3       PG04 -62.222118 -58.592014      294.3     18
4       PG05 -62.227069 -58.598800      247.9     91
5       PG06 -62.229879 -58.606324      223.7    110
6       PG07 -62.235228 -58.616384      188.6    113
7       PG08 -62.235664 -58.623240      159.1    114
8       PG09 -62.235806 -58.629598      121.0    114
9       PG11 -62.199141 -58.581200      465.6      8
10      PG12 -62.205504 -58.581442      409.9     12
11      PG13 -62.213931 -58.583166      357.8     10
12      PG14 -62.220634 -58.587965      320.2     31
13      PG15 -62.225301 -58.595250      263.9     93
14  PG16_AWS -62.235946 -58.613468      194.5    114
15      PG16 -62.230671 -58.600963      229.4    108
16      PG17 -62.236377 -58.621411      167.2    116
17      PG18 -62.237110 -58.628262      131.4    116
18      PG19 -62.237672 -58.633624       96.8    117

In [49]:
df['Year'] = df.index.year

In [50]:
label_year = df.drop_duplicates(subset=['Year']).reset_index()[['Year']]

In [52]:
num_obs = []
for i in label_year['Year']:
    stake  = df.loc[lambda df1: df1['Year'] == i, :].copy().reset_index()
    num_obs.append(stake['Year'].count())

In [53]:
label_year['n_obs'] = num_obs

In [54]:
label_year.sort_values(by=['Year'], inplace=True)
label_year.reset_index(inplace=True)
label_year

   index  Year  n_obs
0      2  2010     46
1      0  2011     81
2      3  2012    349
3      1  2013    292
4      4  2014    275
5      5  2015    204
6      6  2016     65

In [337]:
smb_test = np.full([label_year['n_obs'].max(), len(label_stake), len(label_year)], np.nan)

In [342]:
for i in label_stake['Stake'][0:1]:
    stake  = df.loc[lambda df1: df1['Stake'] == i, :].copy().reset_index()
    year = 0
    for j in label_year['Year']:
        stake1  = stake.loc[lambda df1: df1['Year'] == j, :].copy().reset_index()
        print(year)
        print(stake1)
        year = year+1

Empty DataFrame
Columns: [index, Date, Stake, Latitude, Longitude, Elevation, Days, SMB, t2m, rh, u2, SWin, LWin, tp, sf, msl, press, tcc, t2m_an, PDD, Year]
Index: []

[0 rows x 21 columns]
0
   index       Date Stake   Latitude  Longitude  Elevation  Days   SMB  \
0      0 2011-03-02  PG01 -62.201488 -58.583236      435.7     0  3.14
1      1 2011-03-07  PG01 -62.201488 -58.583236      435.7     5 -3.03
2      2 2011-03-09  PG01 -62.201488 -58.583236      435.7     2  0.10

        t2m        rh  ...       SWin       LWin        tp        sf  \
0 -0.842712  88.92846  ...  193.75117  262.32993  0.002159  0.001920
1 -1.547089  91.56166  ...  103.99137  288.65213  0.039459  0.015694
2 -2.051198  93.91679  ...   71.61935  300.07703  0.016366  0.007262

         msl      press       tcc    t2m_an  PDD  Year
0  988.82900  938.89734  0.569043  1.283319  0.0  2011
1  984.74524  934.99945  0.884296  1.111962  0.0  2011
2  986.69165  936.83850  0.940137  0.989325  0.0  2011

[3 rows x 21 columns]
1
Empty DataFrame
Columns: [index, Date, Stake, Latitude, Longitude, Elevation, Days, SMB, t2m, rh, u2, SWin, LWin, tp, sf, msl, press, tcc, t2m_an, PDD, Year]
Index: []

[0 rows x 21 columns]
2
   index       Date Stake   Latitude  Longitude  Elevation  Days   SMB  \
0      3 2013-02-11  PG01 -62.201488 -58.583236      435.7   705  0.05
1      4 2013-02-19  PG01 -62.201488 -58.583236      435.7     8 -0.08
2      5 2013-02-27  PG01 -62.201488 -58.583236      435.7     8 -0.01

        t2m        rh  ...       SWin       LWin        tp        sf  \
0 -6.571172  87.57374  ...  101.99141  264.68054  3.118673  2.830668
1 -2.980143  88.86776  ...  137.89722  287.33777  0.042275  0.034477
2 -3.258023  85.84771  ...  163.34926  263.86685  0.024564  0.021192

          msl      press       tcc    t2m_an  PDD  Year
0   990.60895  940.44910  0.847065 -0.110270  0.0  2013
1   981.61755  931.99060  0.897450  0.763336  0.0  2013
2  1001.60364  950.96277  0.673365  0.695735  0.0  2013

[3 rows x 21 columns]
3
Empty DataFrame
Columns: [index, Date, Stake, Latitude, Longitude, Elevation, Days, SMB, t2m, rh, u2, SWin, LWin, tp, sf, msl, press, tcc, t2m_an, PDD, Year]
Index: []

[0 rows x 21 columns]
4
Empty DataFrame
Columns: [index, Date, Stake, Latitude, Longitude, Elevation, Days, SMB, t2m, rh, u2, SWin, LWin, tp, sf, msl, press, tcc, t2m_an, PDD, Year]
Index: []

[0 rows x 21 columns]
5
Empty DataFrame
Columns: [index, Date, Stake, Latitude, Longitude, Elevation, Days, SMB, t2m, rh, u2, SWin, LWin, tp, sf, msl, press, tcc, t2m_an, PDD, Year]
Index: []

[0 rows x 21 columns]
6

In [268]:
lsygo_test_matrixes, lsygo_train_matrixes = [],[]
n_folds = 20
random_years = np.random.randint(0, 6, n_folds) # Random year idxs
random_glaciers = np.random.randint(0, 11, n_folds) # Random glacier indexes

In [273]:
for i in range(0, n_folds):
    
    test_matrix  = np.zeros((11, 6), dtype=np.int8)
    train_matrix = np.ones((11, 6), dtype=np.int8)

    print("\nChosen stake: " + str(random_glaciers[i]))
    print("Chosen year: " + str(random_years[i]))
    # Fill test matrix
    test_matrix[random_glaciers[i], :] = 1
    # Fill train matrix
    train_matrix[random_glaciers[i], :] = 0
    
    # Fill test matrix
    test_matrix[:, random_years[i]] = 1
    
    # Fill train matrix
    train_matrix[:, random_years[i]] = 0

    # Add matrixes to folds
    lsygo_test_matrixes.append(test_matrix)
    lsygo_train_matrixes.append(train_matrix)

Chosen stake: 10
Chosen year: 4

Chosen stake: 5
Chosen year: 4

Chosen stake: 5
Chosen year: 5

Chosen stake: 0
Chosen year: 3

Chosen stake: 6
Chosen year: 2

Chosen stake: 4
Chosen year: 1

Chosen stake: 6
Chosen year: 0

Chosen stake: 6
Chosen year: 0

Chosen stake: 2
Chosen year: 1

Chosen stake: 3
Chosen year: 3

Chosen stake: 9
Chosen year: 1

Chosen stake: 10
Chosen year: 1

Chosen stake: 3
Chosen year: 2

Chosen stake: 8
Chosen year: 4

Chosen stake: 2
Chosen year: 0

Chosen stake: 6
Chosen year: 4

Chosen stake: 2
Chosen year: 3

Chosen stake: 5
Chosen year: 0

Chosen stake: 1
Chosen year: 4

Chosen stake: 5
Chosen year: 3

In [287]:
lsygo_test_matrixes[1]

array([[0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0]], dtype=int8)

In [323]:
x = np.linspace(0,0.2, 6)
y = np.linspace(0,0.2, 11)
smb = np.meshgrid(x,y)[1]
smb_test = np.full([2, 11, 6], 1)
smb_test

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [332]:
#print((smb_test[:,lsygo_test_matrixes[0].astype(bool)]))
print((smb_test[:,lsygo_train_matrixes[0].astype(bool)]))

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

In [114]:
# Fill test matrix
test_matrix[glacier_idx, :] = 1
# Fill train matrix
train_matrix[glacier_idx, :] = 0

# Fill test matrix
test_matrix[:, year_idx] = 1

# Fill train matrix
train_matrix[:, year_idx] = 0

# Add matrixes to folds
lsygo_test_matrixes.append(test_matrix)
lsygo_train_matrixes.append(train_matrix)

year_idx = year_idx+4
glacier_idx = glacier_idx+4

In [ ]:
# Add matrixes to folds
lsygo_test_matrixes.append(test_matrix)
lsygo_train_matrixes.append(train_matrix)

year_idx = year_idx+4
glacier_idx = glacier_idx+4

In [70]:
#smb_year_stake = np.full([3, 7, 5], np.nan)
#smb_year_stake

In [2]:
lsygo_test_matrixes, lsygo_train_matrixes = [],[]
year_idx = 0
glacier_idx = 0

# LSYGO folds
#np.random.seed(10)
n_folds = 5
#    n_folds = 100
random_years = np.random.randint(0, 5, n_folds*6) # Random year idxs
random_glaciers = np.random.randint(0, 3, n_folds*6) # Random glacier indexes

In [3]:
for fold in range(1, n_folds+1):
    test_matrix, train_matrix = np.zeros((3, 5), dtype=np.int8), np.ones((3, 5), dtype=np.int8)

    year_choice = []
    for i in range(0, 4):
        year_choice.append(random_years)

    print("Chosen years: " + str(year_choice))

    # Fill test matrix
    # 1
    test_matrix[random_glaciers[glacier_idx], year_choice[0]] = 1
    test_matrix[random_glaciers[glacier_idx], year_choice[1]] = 1
    test_matrix[random_glaciers[glacier_idx], year_choice[2]] = 1
    test_matrix[random_glaciers[glacier_idx], year_choice[3]] = 1

    # 2
    test_matrix[random_glaciers[glacier_idx+1], year_choice[0]] = 1
    test_matrix[random_glaciers[glacier_idx+1], year_choice[1]] = 1
    test_matrix[random_glaciers[glacier_idx+1], year_choice[2]] = 1
    test_matrix[random_glaciers[glacier_idx+1], year_choice[3]] = 1

    # 3
    test_matrix[random_glaciers[glacier_idx+2], year_choice[0]] = 1
    test_matrix[random_glaciers[glacier_idx+2], year_choice[1]] = 1
    test_matrix[random_glaciers[glacier_idx+2], year_choice[2]] = 1
    test_matrix[random_glaciers[glacier_idx+2], year_choice[3]] = 1

    # 4
    test_matrix[random_glaciers[glacier_idx+3], year_choice[0]] = 1
    test_matrix[random_glaciers[glacier_idx+3], year_choice[1]] = 1
    test_matrix[random_glaciers[glacier_idx+3], year_choice[2]] = 1
    test_matrix[random_glaciers[glacier_idx+3], year_choice[3]] = 1

    # Fill train matrix
    train_matrix[random_glaciers[glacier_idx], :] = 0
    train_matrix[random_glaciers[glacier_idx+1], :] = 0
    train_matrix[random_glaciers[glacier_idx+2], :] = 0
    train_matrix[random_glaciers[glacier_idx+3], :] = 0

    train_matrix[:, year_choice[0]] = 0
    train_matrix[:, year_choice[1]] = 0
    train_matrix[:, year_choice[2]] = 0
    train_matrix[:, year_choice[3]] = 0

    year_idx = year_idx+4
    glacier_idx = glacier_idx+4
    print('train')
    print(train_matrix)
    print('test')
    print(test_matrix)

Chosen years: [array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4])]
train
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
test
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Chosen years: [array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4])]
train
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
test
[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]
Chosen years: [array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4])]
train
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
test
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]
Chosen years: [array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4])]
train
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
test
[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]
Chosen years: [array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4]), array([1, 0, 2, 3, 4, 1, 1, 3, 3, 1, 1, 3, 1, 2, 4, 1, 2, 3, 0, 0, 3, 0,
       3, 2, 1, 4, 0, 2, 3, 4])]
train
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
test
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]

In [4]:
test_matrix

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)